language: python

python:
  - "3.6"

addons:
  postgresql: "11"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database epic_db;' -U postgres

script:
  - pytest --cov=api
  - coverage 
  - coveralls    
after_script:
  - coveralls
  - coverage 
after_success:
  - codecov
  - coveralls
  - coverage