language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database travis_epic_db;' -U postgres

addons:
  postgresql: "11"

env:
  global:
    - APP_SETTING=staging
    - DATABASE_URL=postgres://postgres:@localhost:5432/travis_epic_db

script:
  - pytest --cov=api
  - coverage 
  - coveralls    
after_script:
  - coveralls
  - coverage 
after_success:
  - codecov
  - coveralls
  - coverage